# Generated by Django 4.2.13 on 2024-08-04 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('company_description', models.TextField(verbose_name='Описание компании')),
                ('company_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон компании')),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email компании')),
                ('company_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес компании')),
                ('company_site', models.URLField(blank=True, null=True, verbose_name='Сайт компании')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
