# Generated by Django 4.2.13 on 2024-08-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('looking-job', 'Ищу работу'), ('resume-analysis', 'Анализ резюме'), ('work-students', 'Работа для студентов'), ('deleting-account', 'Удаление аккаунта'), ('other', 'Другое')], max_length=16, verbose_name='Тема обращения')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=100, verbose_name='Электронная почта')),
                ('description', models.TextField(verbose_name='Обязанности')),
                ('ticket_file', models.FileField(blank=True, default=None, null=True, upload_to='ticket/%Y/%m/%d', verbose_name='Дополнительные данные')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заявки')),
            ],
        ),
    ]
