# Generated by Django 4.2.13 on 2024-08-06 12:07

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_date_update_service_date_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionally',
            name='minimum_order',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='RUB', max_digits=10, null=True, verbose_name='Минимальная сумма заказа'),
        ),
    ]
