# Generated by Django 4.2.13 on 2024-08-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_email_alter_service_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='estimation',
            field=models.IntegerField(choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')], default=5, verbose_name='Оценка'),
        ),
    ]
