# Generated by Django 4.2.13 on 2024-08-10 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_feedback_estimation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionally',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additionally', to='services.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='experience',
            field=models.CharField(choices=[('without-experience', 'Без опыта'), ('less-than-year', 'Менее года'), ('1', '1 год'), ('2', '2 года'), ('3', '3 года'), ('4', '4 года'), ('5', '5 лет'), ('6', '6 лет'), ('7', '7 лет'), ('8', '8 лет'), ('9', '9 лет'), ('10', '10 лет'), ('more-than-10', 'Более 10 лет')], max_length=18, verbose_name='Опыт работы'),
        ),
    ]
