# Generated by Django 4.2.13 on 2024-08-10 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления вакансии'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания вакансии'),
            preserve_default=False,
        ),
    ]
