# Generated by Django 4.2.13 on 2024-08-10 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_vacancy_date_update_vacancy_date_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditions',
            name='vacancy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='vacancy.vacancy'),
        ),
    ]
