# Generated by Django 4.2.13 on 2024-08-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_remove_portfolio_image_alter_portfolio_resume_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='experience',
            field=models.CharField(choices=[('without-experience', 'Без опыта'), ('less-than-year', 'Менее года'), ('1', '1 год'), ('2', '2 года'), ('3', '3 года'), ('4', '4 года'), ('5', '5 лет'), ('6', '6 лет'), ('7', '7 лет'), ('8', '8 лет'), ('9', '9 лет'), ('10', '10 лет'), ('more-than-10', 'Более 10 лет')], max_length=18, verbose_name='Стаж'),
        ),
    ]
