# Generated by Django 4.2.13 on 2024-08-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_resume_email_alter_resume_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_date',
            field=models.DateField(blank=True, max_length=8, null=True, verbose_name='Дата начала работы'),
        ),
    ]
