# Generated by Django 4.2.13 on 2024-08-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_workexperience_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalskills',
            name='skills',
            field=models.TextField(blank=True, null=True, verbose_name='Навыки'),
        ),
    ]
