"""
Django settings for staffsearch project.

Generated by 'django-admin startproject' using Django 4.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f15#l@tk5zcj@m*%od6@ygj0gjc17bi@9gw2q8ft%8l$p_bv2p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1"]
INTERNAL_IPS = ["127.0.0.1"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'resume.apps.ResumeConfig',
    'info.apps.InfoConfig',
    'users.apps.UsersConfig',
    'services.apps.ServicesConfig',
    'vacancy.apps.VacancyConfig',
    'help.apps.HelpConfig',

    'djmoney',
    "debug_toolbar",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "debug_toolbar.middleware.DebugToolbarMiddleware",
]

ROOT_URLCONF = 'staffsearch.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'staffsearch.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # Движок базы данных MySQL
        'NAME': 'staff_search_db',  # Имя базы данных
        'USER': 'root',  # Имя пользователя БД
        'PASSWORD': '12345',  # Пароль пользователя БД
        'HOST': '127.0.0.1',  # Адрес сервера базы данных (локальный)
        'PORT': '3306',  # Порт, используемый для подключения к MySQL
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'  # URL для доступа к статическим файлам

STATIC_ROOT = BASE_DIR / "staticfiles"  # Путь к директории, где будут собраны статические файлы

STATICFILES_DIRS = [
    BASE_DIR / "static",  # Путь к общим статическим файлам
]

MEDIA_ROOT = BASE_DIR / 'media'  # Директория для загрузки пользовательских медиафайлов
MEDIA_URL = '/media/'  # URL для доступа к медиафайлам

# Тип поля первичного ключа по умолчанию
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'  # Использование BigAutoField для первичных ключей

DEFAULT_USER_IMAGE = STATIC_URL + 'img/default.png'  # Путь к изображению пользователя по умолчанию
DEFAULT_IMAGE = STATIC_URL + 'img/default_img.png'  # Путь к изображению по умолчанию

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Стандартный бэкенд аутентификации Django
    'users.authentication.EmailAuthBackend',  # Пользовательский бэкенд аутентификации по email
]

LOGIN_REDIRECT_URL = 'index'  # URL для перенаправления после успешной авторизации

LOGOUT_REDIRECT_URL = 'index'  # URL для перенаправления после выхода из аккаунта

LOGIN_URL = 'users:login'  # URL для перенаправления пользователя на страницу авторизации, если требуется вход
